### ISSUE TITLE
November Checklist

### ISSUE THREAD

**Issue by mannylopez** [maptime/portland#16]
- [x] Secure space
- [x] Secure speaker
- [x] Food and drinks
- [x] Meetup
- [x] Calagator
- [x] maptime.io

**Comment by mannylopez** [comment]
[Meetup](http://www.meetup.com/MaptimePDX/events/226379684/)
[Calagator](http://calagator.org/events/1250469313)
[maptime.io/portland](http://maptime.io/portland/)

**Comment by geografa** [comment]
\o/

**Comment by geografa** [comment]
actually, just remembered we need a quick and dirty slide preso for the start of Maptime. Possibly some slides showing:
- [ ] intro us and presenters
- [ ] intro to maptime
- [ ] thank sponsors
- [ ] announce next week
- [ ] stickers
- [ ] call for next month suggestions

**Comment by mannylopez** [comment]
\o/
