### ISSUE TITLE
April Social Checklist

### ISSUE THREAD

**Issue by geografa** [maptime/portland#32]
**2 weeks out**
- [x] meetup posted
- [x] tweet

**1 week out**
- [x] tweet
- [x] sync with Molly Vogt on food/drink order
- [x] post to blog
- [x] calagator

**3 days out**
- [x] pre-order food and drinks
- [x] check in with WeWork on space/tables/mic
- [x] organize lightening talks
- [ ] tweet schedule of talks

/cc @mannylopez @mattsayler

**Comment by molvo** [comment]
Can the default MaptimePDX page http://maptime.io/portland/ be updated to show the April social announcement?

**Comment by geografa** [comment]
all good @molvo

**Comment by geografa** [comment]
@molvo I have an additional sponsorship from Mapbox so I'm putting in an order for snacks for Monday in addition to pizza. Any thoughts for what to add to the list? Will pizza come with plates, napkins, cups for drinks, etc? or should we get those separate?

**Comment by molvo** [comment]
@geografa Thank you, awesome! I was going to ask you for recommendations on a pizza source and how you've done this in the past - or any guidelines that might be specific to WeWork. Do you have the pizza delivered? When I've done pizzas for groups, I've had it delivered and I've purchased plates and napkins separately and I'm happy to do that again if that seems appropriate. I will plan to arrive around 6:15.

**Comment by molvo** [comment]
@geografa Tim Welch agreed to give a lightning talk. I can bring some stuff to show/talk about or I can just introduce the ORURISA side of things and the YPs who will be there (Madeline Steele for example). I hope and assume you'll present something :)  Do you have folks lined up for lightning talks or other presentations? Do we need to recruit?

**Comment by geografa** [comment]
@molvo I'll just include plates and napkins in the order. For pizza, we're looking at 40 registered so far and will expect many more. I'd make one or two vegan, and more veggie than meat. The [pizza calculator](http://calculate-this.com/how-many-pizzas-buy-calculator) is handy here.

For talks, the registration asks if the registrant would be interested in giving a short preso. I will likely talk about Maptime in general and then later about our new docs and show some GL JS examples. With the 3 of us, there should be time for one or two more if there are last minute talks.

**Comment by molvo** [comment]
Thanks. Quick clarifications: You'll include plates and napkins in the order (from...?)? Or you mean I should include them in the pizza order?
Do you have a recommended pizza source?

**Comment by geografa** [comment]
@molvo Sorry - I'll order: 
- plates 
- napkins 
- sodas

from Instacart. I think pizza can arrive by 6:30p. I'm checking on beer cooler situation.

For pizza providers:
- Hot Lips (preferred)
- Sizzle pie - don't take advance orders
- Pizza Schmizza (haven't worked with them in the past)

**Comment by molvo** [comment]
@geografa Great, I'll order pizza from hot lips. I'm just using my $300 for as much pizza and beer as I can get, right? I can afford ~10 large pizzas and 6 6-packs of decent beer. Still working on upping the budget but $300 is the annual budget for the YPs group (same for other sections), so it's a pretty big commitment for URISA already, not confident I can get more.

**Comment by geografa** [comment]
@molvo sounds great. Here's my order list for today:
- [x] 4 bags chips and salsa
- [ ] assortment of fruit
- [x] case of soda
- [x] 2 bottles of red wine
- [x] 2 bottles of white wine
- [x] napkins and utensils

If you think it makes it any easier, we can put the beer on the Instacart order so it all just gets delivered. I feel like I'm missing something else so let me know if you come up with anything else!

**Comment by molvo** [comment]
Hi! did you put in the order already? busy weekend, sorry i missed the prompt to answer about the beer. let me know if you can add it - if not i can get it there by 6:30 no problem...

**Comment by geografa** [comment]
@molvo sorry - they don't deliver beer so stopped by store and just picked up the wine. Let me know if you run out of time. Will text if anything else comes up.

**Comment by molvo** [comment]
Not a problem at all! I will grab the beer. Pizza has been ordered.
See you tonight.

**Comment by geografa** [comment]
@molvo @tdoubleuu - if you have links to your slides or projects, I'm going to email the Meetup and will share them with the recap.

**Comment by geografa** [comment]
sent!

**Comment by molvo** [comment]
I can send my slides... Landed in DC.this morning for a meeting, have not
had a chance to clear my books and catchup on email...

**Comment by geografa** [comment]
no worries @molvo. I can always tweet from MaptimePDX if you find the bandwidth but I wouldn't worry about it too much :) Have a great time in DC.

**Comment by molvo** [comment]
@geografa I added image credits throughout. any suggestions on where to post the file so it can be linked? I don't maintain a public portfolio or resources <sigh, sorry> and no obvious place on the city's servers...

**Comment by geografa** [comment]
@molvo - I can add to https://github.com/maptime/portland/tree/gh-pages/presentations
